$subscription=@("POSTE-CORPORATE-PRODUZIONE",
"POSTE-COMMONS-CERTIFICAZIONE",
"POSTE-PRODUZIONE",
"POSTE-PIAF-SVILUPPO",
"POSTE-DEAANALYTICS-SVIL",
"POSTE-DIGITAL-PRODUZIONE",
"POSTE-CUSTOMERANALYTICS-SVILUPPO",
"POSTE-PCL-CERTIFICAZIONE",
"POSTE-AMLANALYTICS-SVILUPPO",
"POSTE-RDC-DR",
"POSTE-DIGITAL-SVILUPPO",
"POSTE-PCL-PRODUZIONE",
"POSTE-ASSICURA-CERTIFICAZIONE",
"POSTE-ENERGYANALYTICS-CERTIFICAZIONE",
"POSTE-CERTIFICAZIONE",
"POSTE-SVILUPPO",
"POSTE-COANALYTICS-SVIL",
"POSTE-ENERGYANALYTICS-PRODUZIIONE",
"POSTE-PRODUZIONE-DR",
"POSTE-BANCOPOSTA-PRODUZIONE",
"POSTE-RDC-CERTIFICAZIONE",
"POSTE-PCL-SVILUPPO",
"POSTE-DATAMGMTLNDZN-SVIL",
"POSTE-SMARTLETTERBOX-CERTIFICAZIONE",
"POSTE-SMARTLETTERBOX-SVILUPPO-EXT",
"POSTE-DIGITAL-CERTIFICAZIONE",
"POSTE-DEAANALYTICS-PROD",
"POSTE-AMLANALYTICS-CERTIFICAZIONE",
"POSTE-CORPORATE-CERTIFICAZIONE",
"POSTE-SMARTLETTERBOX-F2-CERTIFICAZIONE-EXT",
"POSTE-BILLINGANALYTICS-SVIL",
"POSTE-DIGITALANALYTICS-SVIL",
"POSTE-SUPPORTANALYTICS-SVIL",
"POSTE-BANCOPOSTA-SVILUPPO",
"POSTE-SMARTLETTERBOX-F2-PRODUZIONE-EXT",
"POSTE-SMARTLETTERBOX-PRODUZIONE-EXT",
"POSTE-CORPORATE-SVILUPPO",
"POSTE-DATAMGMTLNDZN-PROD",
"POSTE-SPID-SVILUPPO",
"POSTE-RDC-PRODUZIONE",
"POSTE-COANALYTICS-PROD",
"POSTE-RDC-SVILUPPO",
"POSTE-SMARTLETTERBOX-F2-SVILUPPO-EXT",
"POSTE-SALESANALYTICS-SVIL",
"POSTE-ASSICURA-SVILUPPO",
"POSTE-AMLANALYTICS-PRODUZIONE",
"POSTE-ENERGYANALYTICS-SVILUPPO",
"POSTE-BANCOPOSTA-CERTIFICAZIONE")

$hash = @{} #Dizionario di tutti i certificati in scadenza

foreach($s in $subscription){
    Set-AzContext -SubscriptionName $s
    
    
    $virtualNewtorks=Get-AzVirtualNetwork
    foreach ($vnet in $virtualNewtorks){
        
        $subnet=Get-AzVirtualNetworkSubnetConfig -VirtualNetwork $vnet

        foreach ($sub in $subnet){
            if ($sub.ServiceAssociationLinks.LinkedResourceType -eq "Microsoft.DBforPostgreSQL/flexibleServers"){
                if($sub.NetworkSecurityGroup -eq $null){
                    $hash.Add($sub.Name,$vnet.Name)
                }
            }
        }
    }
    
}
#Crea CSV
$hash.GetEnumerator() |Select Name,Value |Export-Csv .\subnet.csv